baseURL = "https://juang970.github.io/"
locale = "en-us"
title = "Juan Gonzalez"
theme = "PaperMod"

# Syntax highlighting settings for code blocks
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
noClasses = false
style = "monokai"

[params]
env = "production"
description = "Juan Gonzalez - Personal Website, Blog, and CV"
author = "Juan Gonzalez"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableThemeToggle = false
defaultTheme = "auto" # auto, dark, or light

[params.profileMode]
enabled = true
title = "Juan Angel Gonzalez Aguirre"
subtitle = "Software Engineer & Researcher | Special Projects @ Wolfram"
imageUrl = "images/profile_pic.jpeg" # Optional: add a profile image URL here
imageWidth = 150
imageHeight = 150
imageTitle = "Juan Gonzalez"

[[params.profileMode.buttons]]
name = "About / CV"
url = "/about"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts"

[[params.socialIcons]]
name = "github"
url = "https://github.com/juang970"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/jgonzalez-aguirre/"

[[params.socialIcons]]
name = "email"
url = "mailto:contact@juan-gonzalez.com"

# Main Menu
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 20

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"
weight = 30
